---
title: "R Notebook"
output: html_notebook
---

```{r} 
#Call Libraries
library(tidyverse)
```


```{r}
#Load Datasets
NYS_tax_credit_used <- read_csv('NYS_Corp_Tax_Credit_data/NYS_tax_credit_used.csv')
NYS_tax_credit_net_income <- read_csv('NYS_Corp_Tax_Credit_data/NYS_tax_credit_net_income.csv')
NYS_tax_credit_taxation_basis <- read_csv('NYS_Corp_Tax_Credit_data/NYS_tax_credit_taxation_basis.csv')
NYS_tax_credit_industry <- read_csv('NYS_Corp_Tax_Credit_data/NYS_tax_credit_industry.csv')
```

```{r}
EDA <- function (df) {
  #print.data.frame(summary(df))
  print(dim(df))
  #print(head(df))
  #df %>% filter(is.na(`Number of Taxpayers`))
}
```

```{r}
for (df in c(NYS_tax_credit_used)) {
  EDA(df)
}
#summary(NYS_tax_credit_used)
```

```{r}
summary(NYS_tax)
head(NYS_tax)
NYS_tax %>% filter(is.na(`Number of Taxpayers`)) 
NYS_tax %>% filter(is.na(`Number of Taxpayers`)) %>% distinct(Notes)
#3146 records have missing values for fields: Number of Taxpayers, Amount of Credit, Percent of Credit, Median Amount of Credit, Mean Amount of Credit due to secrecy laws (Notes section contains /d for all of them). These records will be omitted.
```

```{r}
NYS_tax %>% filter(str_detect(Notes, 'd')) %>% drop_na('Number of Taxpayers') #%>% distinct(`Number of Taxpayers`)

#An additional 166 records contain missing values for Median Amount of Credit, but report real values for all other fields, thus these will be kept for analysis.
```

```{r}
NYS_tax_neg <- NYS_tax %>% filter(`Used Group` == 'Negative')

NYS_tax_neg %>% distinct(`Number of Taxpayers`)
NYS_tax_neg %>% select(`Amount of Credit`) %>% distinct()
NYS_tax %>% select(`Credit Type`, `Used Group`, `Amount of Credit`, `Number of Taxpayers`)
```



Net Income dataset analysis
```{r}
dim(NYS_tax_credit_net_income)
head(NYS_tax_credit_net_income, 12)
NYS_tax_credit_net_income %>% select(`ENI Group`) %>% distinct() #10 different ENI Groups including the Total (so essentially 9)
NYS_tax_credit_net_income %>% filter(`Credit Name` == 'Alcoholic Beverage Production Credit', `Credit Type` == 'Credit Earned') %>% group_by(`ENI Group`) %>% summarise(sum(`Number of Taxpayers`, na.rm = T))

#str_detect(Notes, 'd')

sum(NYS_tax_credit_net_income$`Number of Taxpayers`, na.rm = T)/2
```

```{r}
NYS_tax_credit_net_income %>% filter(`Credit Name` == 'Alcoholic Beverage Production Credit', `Credit Type` == 'Credit Earned')
```



Industry dataset analysis

```{r}
dim(NYS_tax_credit_industry)
head(NYS_tax_credit_industry)
NYS_tax_credit_industry %>% select(`NAICS Description`) %>% distinct() #23 different industries including the Total field (therefore essentially 22)
NYS_tax_credit_industry %>% filter(`Credit Type` == 'Credit Earned') %>% group_by(`NAICS Description`) %>% summarise(n = sum(`Number of Taxpayers`, na.rm = T)) %>% arrange(desc(n)) #Manufacturing has the greatest number of taxpayers with 20807 followed by 'Real Estate and Rental and Leasing' and 'Professional, Scientific, and Technical Services' with 11811 and 5117 respectively. 

NYS_tax_credit_industry %>% filter(`Credit Type` == 'Credit Earned') %>% group_by(`NAICS Description`) %>% summarise(n = sum(`Number of Taxpayers`, na.rm = T), credit = sum(`Amount of Credit`, na.rm = T)) %>% mutate(ratio = credit/n) %>% arrange(desc(ratio))
```
```{r}
plot(NYS_tax_credit_industry)
plot(NYS_tax_credit_industry %>% select(`Tax Year`, `Credit Name`, `Number of Taxpayers`, `Amount of Credit`))
```

```{r}
head(NYS_tax_credit_taxation_basis)
```

