---
title: "R Notebook"
output: html_notebook
---
Call Libraries
```{r} 
library(tidyverse)
library(caret)
library(PerformanceAnalytics)
```

Load Datasets
```{r}
NYS_tax_credit_used <- read_csv('NYS_Corp_Tax_Credit_data/NYS_tax_credit_used.csv')
NYS_tax_credit_net_income <- read_csv('NYS_Corp_Tax_Credit_data/NYS_tax_credit_net_income.csv')
NYS_tax_credit_taxation_basis <- read_csv('NYS_Corp_Tax_Credit_data/NYS_tax_credit_taxation_basis.csv')
NYS_tax_credit_industry <- read_csv('NYS_Corp_Tax_Credit_data/NYS_tax_credit_industry.csv')
```


Credit Used Dataset Analysis
```{r}
NYS_tax_credit_net_income %>% select(`Tax Year`) 
summary(NYS_tax)
head(NYS_tax)
NYS_tax_credit_used %>% filter(is.na(`Number of Taxpayers`)) 
NYS_tax_credit_used %>% filter(is.na(`Number of Taxpayers`)) %>% distinct(Notes)
#3146 records have missing values for fields: Number of Taxpayers, Amount of Credit, Percent of Credit, Median Amount of Credit, Mean Amount of Credit due to secrecy laws (Notes section contains /d for all of them). These records will be omitted.
```

```{r}
NYS_tax_credit_used %>% filter(str_detect(Notes, 'd')) %>% drop_na('Number of Taxpayers') #%>% distinct(`Number of Taxpayers`)

#An additional 166 records contain missing values for Median Amount of Credit, but report real values for all other fields, thus these will be kept for analysis.
```

```{r}
NYS_tax_neg <- NYS_tax_credit_used %>% filter(`Used Group` == 'Negative')

NYS_tax_neg %>% distinct(`Number of Taxpayers`)
NYS_tax_neg %>% select(`Amount of Credit`) %>% distinct()
NYS_tax_credit_used %>% select(`Credit Type`, `Used Group`, `Amount of Credit`, `Number of Taxpayers`)
```


Net Income Dataset Analysis
```{r}
dim(NYS_tax_credit_net_income)
head(NYS_tax_credit_net_income, 12)
summary(NYS_tax_credit_net_income)
NYS_tax_credit_net_income %>% select(`Credit Name`) %>% distinct() %>% arrange(`Credit Name`) #10 different ENI Groups including the Total (so essentially 9)
NYS_tax_credit_net_income %>% filter(`Credit Name` == 'Alcoholic Beverage Production Credit', `Credit Type` == 'Credit Earned') %>% group_by(`ENI Group`) %>% summarise(sum(`Number of Taxpayers`, na.rm = T))

#str_detect(Notes, 'd')

sum(NYS_tax_credit_net_income$`Number of Taxpayers`, na.rm = T)/2
```
Cleaning up Credit Names
```{r}
NYS_tax_credit_net_income %>% select(`Credit Name`) %>% distinct() %>% arrange(`Credit Name`) %>% head(2) %>% mutate(str_length(`Credit Name`))

NYS_tax_credit_net_income %>% mutate(`Credit Name` = ifelse(str_starts(`Credit Name`, 'Alcoholic'), 'Alcoholic Beverage Production Credit', `Credit Name`), `Credit Name` = ifelse(str_starts(`Credit Name`, 'Manufacture'), 'Real Property Tax Relief Credit for Manufacturing', `Credit Name`)) %>% select(`Credit Name`) %>% distinct() %>% arrange(`Credit Name`)

```

```{r}
table(NYS_tax_credit_net_income %>% filter(`Credit Type` == 'Credit Earned', `ENI Group` == 'Total') %>% select(`Amount of Credit`))
dim(NYS_tax_credit_net_income %>% filter(`Credit Type` == 'Credit Earned', `ENI Group` == 'Total') %>% select(`Amount of Credit`))
```

Maximum # of Taxpayers Credit Name, Type and Year
```{r}
NYS_tax_credit_net_income %>% select(`Tax Year`, `Credit Type`, `Credit Name`, `ENI Group`, `Number of Taxpayers`) %>% filter(`Number of Taxpayers` == max(`Number of Taxpayers`, na.rm = T))
```

```{r}
NYS_tax_credit_net_income %>% filter(`Credit Name` == 'Alcoholic Beverage Production Credit', `Credit Type` == 'Credit Earned')
```

Understanding Percent of Credit field
```{r}
NYS_tax_credit_net_income #%>% filter(`Credit Type` == 'Credit Earned', `Credit Name` == 'Alcoholic Beverage Production Credit') %>% select(`Tax Year`, `ENI Group`, `Amount of Credit`, `Percent of Credit`)
```

Checking Credit Claimed vs Credit Earned
```{r}
NYS_tax_credit_net_income %>% filter(`Credit Type` %in% c('Credit Earned', 'Credit Claimed')) %>% select(`Tax Year`, `Tax Article`, `Credit Type`, `Credit Name`, `ENI Group`, `Amount of Credit`)
```






**Sandbox** Logistic regression for ENI dataset
```{r}
# income_cleaned %>% select(Name) %>% distinct()
# for (i in income_cleaned['Name']) {
#   income_cleaned %>% mutate(str_sub(income_cleaned[['Name']], 1, 7) = ifelse(Name == str_sub(income_cleaned[['Name']], 1, str_length(income_cleaned[['Name']]))))
# }
# 
# 
# income_cleaned %>% mutate(str_sub(income_cleaned[['Name']], 1, 7) = ifelse(Name == str_sub(income_cleaned[['Name']], 1, str_length(income_cleaned[['Name']]))))
# ?mutate()
# str_replace()
# 
# str_sub(income_cleaned[['Name']], 1, str_length(income_cleaned[['Name']]))
# 
# str_length(income_cleaned[['Name']])
# 
# str_sub(income_cleaned[['Name']], 1, 7)
# ?str_sub()
# 
# income_cleaned %>% mutate(Alcohol = ifelse(Name == 'Alcoholic Beverage Production Credit', 1, 0), 
#                           Alt_Fuels_Elec = ifelse(Name == 'Alternative Fuels and Electric Vehicle Recharging Property Credit', 1, 0), 
#                           Alt_Fuels = ifelse(Name == 'Alternative Fuels Credit', 1, 0),
#                           Alt_Min = ifelse(Name == 'Alternative Minimum Tax Credit', 1, 0))
#   
#   
# logit.overall = glm(Avg ~ . -Amount, family = 'binomial', data = income_cleaned)
# summary(logit.overall)
```





Industry dataset analysis
```{r}
dim(NYS_tax_credit_industry)
head(NYS_tax_credit_industry)
NYS_tax_credit_industry %>% select(`NAICS Description`) %>% distinct() #23 different industries including the Total field (therefore essentially 22)
NYS_tax_credit_industry %>% filter(`Credit Type` == 'Credit Earned') %>% group_by(`NAICS Description`) %>% summarise(n = sum(`Number of Taxpayers`, na.rm = T)) %>% arrange(desc(n)) #Manufacturing has the greatest number of taxpayers with 20807 followed by 'Real Estate and Rental and Leasing' and 'Professional, Scientific, and Technical Services' with 11811 and 5117 respectively. 

NYS_tax_credit_industry %>% filter(`Credit Type` == 'Credit Earned') %>% group_by(`NAICS Description`) %>% summarise(Num = sum(`Number of Taxpayers`, na.rm = T), Amount = sum(`Amount of Credit`, na.rm = T)) %>% mutate(Avg = Amount/Num) %>% arrange(desc(Avg)) #displaying Avg amount of credit earned per taxpayer per industry
```

```{r}
plot(NYS_tax_credit_industry)
plot(NYS_tax_credit_industry %>% select(`Tax Year`, `Credit Name`, `Number of Taxpayers`, `Amount of Credit`))
```

```{r}
summary(NYS_tax_credit_industry)
NYS_tax_credit_industry %>% filter(is.na(`Number of Taxpayers`)) #4003 records with NAs for Number of Taxpayers, Amount of Credit, Percent of Credit, Mean Amount of Credit
```










***SHINY PREP SECTION***


```{r}
NYS_tax_credit_net_income %>% group_by(`ENI Group`) %>% summarise(Max = max(`Mean Amount of Credit`, na.rm = T), Min = min(`Mean Amount of Credit`, na.rm = T), Mean = mean(`Mean Amount of Credit`, na.rm = T)) %>% arrange(desc(Mean))
```
```{r}
head(NYS_tax_credit_net_income)
NYS_tax_credit_net_income %>% filter(`Number of Taxpayers` > 0) %>% mutate(`Number of Taxpayers` = log(`Number of Taxpayers` + 1)) %>% select(`Tax Year`, `Number of Taxpayers`, `Amount of Credit`, `Mean Amount of Credit`) %>% chart.Correlation(histogram = T)
```

```{r}
dim(NYS_tax_credit_net_income)
missing_values <- NYS_tax_credit_net_income %>% filter(is.na(`Number of Taxpayers`) | `Number of Taxpayers` == 0) #13775 records contain NAs or 0s
NYS_tax_credit_net_income %>% filter(is.na(`Number of Taxpayers`) | `Number of Taxpayers` == 0, str_detect(Notes, 'd')) #2772 NAs or 0s are based on privacy (Notes contain /d)

as.data.frame(table(missing_values$`ENI Group`, missing_values$`Credit Type`)) %>% pivot_wider(values_from = Freq, names_from = Var2) %>% arrange(desc(`Credit Carried Forward`))
as.data.frame(table(missing_values$`ENI Group`, missing_values$`Credit Name`)) %>% pivot_wider(values_from = Freq, names_from = Var2)
```
```{r}
NYS_tax_credit_net_income %>% mutate(log_taxpayers = log(`Number of Taxpayers` + 1)) %>% filter(log_taxpayers > 0) %>% ggplot(aes(`log_taxpayers`)) + geom_histogram() + facet_wrap(~ `ENI Group`)

NYS_tax_credit_net_income %>% mutate(log_taxpayers = log(`Number of Taxpayers` + 1)) %>% filter(log_taxpayers > 0) %>% ggplot(aes(`log_taxpayers`)) + geom_histogram() + facet_wrap(~ `Tax Year`) #Number of taxpayers increases dramatically after 2011
```
```{r}
NYS_tax_credit_net_income %>% mutate(log_taxpayers = log(`Number of Taxpayers` + 1)) %>% filter(log_taxpayers > 0) %>% ggplot(aes(`log_taxpayers`)) + geom_histogram() + facet_wrap(~ `Credit Name`)
```
```{r}
NYS_tax_credit_net_income %>% filter(`Mean Amount of Credit` > 0) %>% mutate(log_mean_amount = log(`Mean Amount of Credit`)) %>% ggplot(aes(log_mean_amount)) + geom_histogram() + facet_wrap(~ `Credit Name`)
```
```{r}
NYS_tax_credit_net_income %>% filter(`Mean Amount of Credit` > 0) %>% mutate(log_mean_amount = log(`Mean Amount of Credit`)) %>% ggplot(aes(log_mean_amount)) + geom_histogram() + facet_wrap(~ `Tax Year`)
```
```{r}
NYS_tax_credit_net_income %>% filter(is.na(`Number of Taxpayers`))
NYS_tax_credit_net_income %>% select(`Tax Year`, `Credit Type`, `Credit Name`, `ENI Group`, `Number of Taxpayers`, `Mean Amount of Credit`) %>% filter(`Tax Year` == 2019, `Credit Name` == 'Investment Tax Credit', `Credit Type` == 'Credit Earned')

NYS_tax_credit_net_income %>% select(`Tax Year`, `Credit Type`, `Credit Name`, `ENI Group`, `Number of Taxpayers`, `Mean Amount of Credit`) %>% filter(`Tax Year` == 2019, ' `Credit Type` == 'Credit Earned')
```

